<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<OutputType>Exe</OutputType>
		<StartupObject>TicketDisplayAppModified.Program</StartupObject>


		<AvaloniaVersion>11.0.0</AvaloniaVersion>
		<!-- Use Avalonia version you want -->
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="11.0.0" />
		<PackageReference Include="Avalonia.Desktop" Version="11.0.0" />
		<PackageReference Include="Avalonia.ReactiveUI" Version="11.0.0" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
		<!-- Include diagnostics only in Debug builds -->
		<PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Views\TicketTemplate.axaml.cs">
	    <DependentUpon>TicketTemplate.axaml</DependentUpon>
	  </Compile>
	</ItemGroup>

</Project>
