<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<OutputType>Exe</OutputType>
		<StartupObject>TicketDisplayAppModified.Program</StartupObject>
		<AvaloniaVersion>11.0.0</AvaloniaVersion>
		<!-- Use Avalonia version you want -->
	</PropertyGroup>

	<PropertyGroup>
		<AssemblyName>TicketAppV1.1.0</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>





	<ItemGroup>
	  <None Remove="large-triangles.svg" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Assets\alternating-arrowhead.png" />
	  <Content Include="Assets\arrowdark.png">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Assets\avalonia-logo.ico" />
	  <Content Include="Assets\cornered-stairs.png">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Assets\repeating-triangles.png">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Assets\sun-tornado.png">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>


	<ItemGroup>
		<PackageReference Include="Avalonia" Version="11.3.2" />
		<PackageReference Include="Avalonia.Desktop" Version="11.3.2" />
		<PackageReference Include="Avalonia.ReactiveUI" Version="11.3.2" />
		<PackageReference Include="Avalonia.Svg" Version="11.3.0" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.2" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.2" />
		<!-- Include diagnostics only in Debug builds -->
		<PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.3.2" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Views\TicketTemplate.axaml.cs">
	    <DependentUpon>TicketTemplate.axaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\RedrawTicketTemplate.axaml.cs">
	    <DependentUpon>RedrawTicketTemplate.axaml</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="ViewModels\" />
	</ItemGroup>

	<ItemGroup>
	  <AvaloniaResource Update="Assets\cornered-stairs.png">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </AvaloniaResource>
	  <AvaloniaResource Update="Assets\dominos.svg">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </AvaloniaResource>
	</ItemGroup>

</Project>
